### ISSUE TITLE
Should request tiles using https when possible 

### ISSUE THREAD

**Issue by easherma** [JackDougherty/leaflet-maps-with-google-sheets#38]
ex. Carto also serves their tiles using https: https://carto.com/location-data-services/basemaps/
I changed the URL accordingly in leaflet-providers.js and it worked fine.

**Comment by JackDougherty** [comment]
@ilyankou please look into this issue, since Chrome protocol now blocks basemaps from http, which means that our map does not show Carto basemaps

I tried changing the URL in leaflet-providers to the https version for Carto described at bottom of this page
https://carto.com/location-data-services/basemaps/

But this simple change did not fix the problem for me. Perhaps the problem is that leaflet-providers forces http ??
https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js#L53

See also why leaflet-providers developer has not yet fixed this issue
https://github.com/leaflet-extras/leaflet-providers/issues
